# Generated by Django 4.1.5 on 2023-04-13 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_test_teachers_test_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teachers',
            name='lang_cert',
        ),
        migrations.RemoveField(
            model_name='teachers',
            name='test_test',
        ),
        migrations.DeleteModel(
            name='LangCert',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
