# Generated by Django 4.1.5 on 2023-04-13 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_remove_teachers_lang_cert_remove_teachers_test_test_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicDegreeTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_of_defense_degree', models.CharField(blank=True, max_length=200, null=True)),
                ('academic_degree_file_degree', models.FileField(blank=True, null=True, upload_to='LangCert/')),
            ],
        ),
        migrations.AddField(
            model_name='teachers',
            name='academic_degree_test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='academic_degree_test_name', to='teachers.academicdegreetest'),
        ),
    ]
