# Generated by Django 4.1.5 on 2023-04-13 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0004_academicdegreetest_teachers_academic_degree_test'),
    ]

    operations = [
        migrations.RenameField(
            model_name='academicdegreetest',
            old_name='academic_degree_file_degree',
            new_name='academic_degree_file_test',
        ),
        migrations.RenameField(
            model_name='academicdegreetest',
            old_name='place_of_defense_degree',
            new_name='place_of_defense_test',
        ),
    ]
