# Generated by Django 4.1.5 on 2023-04-13 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0005_rename_academic_degree_file_degree_academicdegreetest_academic_degree_file_test_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LanguageCert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cert_type', models.CharField(blank=True, max_length=200, null=True)),
                ('cert_score', models.CharField(blank=True, max_length=200, null=True)),
                ('cert_file', models.FileField(blank=True, null=True, upload_to='langCert/')),
            ],
        ),
        migrations.RemoveField(
            model_name='teachers',
            name='academic_degree_test',
        ),
        migrations.DeleteModel(
            name='AcademicDegreeTest',
        ),
        migrations.AddField(
            model_name='teachers',
            name='language_cert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='language_cert_name', to='teachers.languagecert'),
        ),
    ]
