# Generated by Django 4.1.5 on 2023-04-20 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0007_remove_teachers_academic_degree_data_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grand_1', models.PositiveIntegerField(default=0)),
                ('grand_2', models.PositiveIntegerField(default=0)),
                ('summa', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='academicdegreedata',
            name='academic_degree_data',
        ),
        migrations.RemoveField(
            model_name='academicrankdata',
            name='academic_rank_data',
        ),
        migrations.RemoveField(
            model_name='languagecert',
            name='language_cert',
        ),
        migrations.AddField(
            model_name='teachers',
            name='academic_degree_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='academic_degree_data_name', to='teachers.academicdegreedata'),
        ),
        migrations.AddField(
            model_name='teachers',
            name='academic_rank_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='academic_rank_data_name', to='teachers.academicrankdata'),
        ),
        migrations.AddField(
            model_name='teachers',
            name='language_cert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='language_cert_name', to='teachers.languagecert'),
        ),
    ]
